- name: huawei-arm64-obs obs workers
  hosts: huawei_arm64_obs
  user: root
  gather_facts: True
  vars:
    swapfile: /swapfile
    obs_worker_instances: 2
    obs_worker_jobs: 6
    container_tag: latest
    obs_repository_server: obs.openhpc.community
  tasks:
  - name: create OBS directories
    file: dest="{{item}}" mode=0755 state=directory
    with_items:
    - /workers/
    - /workers/cache

  - name: install packages
    package:
      state: present
      name:
      - podman

  - name: check for swapfile
    stat: path={{ swapfile }}
    register: swapfile_status

  - name: create swapfile
    command: "fallocate -l 12G {{ swapfile }}"
    when: not swapfile_status.stat.exists

  - name: change swapfile permission
    file: path={{ swapfile }}
          owner=root
          group=root
          mode=0600

  - name: format swapfile
    command: "mkswap {{ swapfile }}"
    when: not swapfile_status.stat.exists

  - name: add swapfile to fstab
    mount: name=none
           src={{ swapfile }}
           fstype=swap
           opts=sw
           passno=0
           dump=0
           state=present

  - name: activate swapfile
    command: "swapon {{ swapfile }}"
    when: ansible_swaptotal_mb < 1

  - name: install obs worker configuration
    template:
      src: obs-server
      dest: /etc/sysconfig/obs-server
      owner: root
      group: root
      mode: 0644

  - name: install obsworker podman service
    template:
      src: obsworker-podman.service
      dest: /etc/systemd/system/obsworker-podman.service
      owner: root
      group: root
      mode: 0644
    register: obsworker_podman_service

  - name: systemd daemon-reload
    ansible.builtin.systemd:
      daemon_reload: true
    when: obsworker_podman_service.changed

  - name: enable obs worker podman service
    service: name=obsworker-podman enabled=yes state=started
