- name: openhpc-lenovo-repo obs workers
  hosts: openhpc_lenovo_repo
  user: root
  gather_facts: True
  vars:
    obs_worker_instances: 4
    obs_worker_jobs: 6
    container_tag: amd64
    obs_repository_server: 10.255.255.0
  tasks:
  - name: create OBS directories
    file: dest="{{item}}" mode=0755 state=directory
    with_items:
    - /workers/
    - /workers/cache

  - name: install packages
    package:
      state: present
      name:
      - podman

  - name: install obs worker configuration
    template:
      src: obs-server
      dest: /etc/sysconfig/obs-server
      owner: root
      group: root
      mode: 0644

  - name: install obsworker podman service
    template:
      src: obsworker-podman.service
      dest: /etc/systemd/system/obsworker-podman.service
      owner: root
      group: root
      mode: 0644
    register: obsworker_podman_service

  - name: systemd daemon-reload
    ansible.builtin.systemd:
      daemon_reload: true
    when: obsworker_podman_service.changed

  - name: enable obs worker podman service
    service: name=obsworker-podman enabled=yes state=started
