- name: OBS worker openhpc-lenovo-jenkins-c3
  hosts: openhpc_lenovo_jenkins_c3
  user: root
  gather_facts: true
  vars:
    obs_worker_instances: 30
    obs_worker_jobs: 6
    container_tag: amd64
    obs_repository_server: 10.255.254.0

  handlers:
    - name: Include handlers
      ansible.builtin.import_tasks: ../common/handlers.yml

  tasks:
    - name: Include history.yml
      ansible.builtin.include_tasks: ../common/history.yml

    - name: Include automatic-updates.yml
      ansible.builtin.include_tasks: ../common/automatic-updates.yml

    - name: Create OBS directories
      ansible.builtin.file:
        dest: "{{ item }}"
        mode: "0755"
        state: directory
      with_items:
        - /workers/

    - name: Mount /workers partition
      ansible.posix.mount:
        path: /workers
        src: UUID=008f4b8a-66a7-40d1-957a-97cb19e3b582
        opts: defaults,noatime
        state: mounted
        fstype: xfs

    - name: Create OBS directories
      ansible.builtin.file:
        dest: "{{ item }}"
        mode: "0755"
        state: directory
      with_items:
        - /workers/cache

    - name: Install packages
      ansible.builtin.package:
        state: present
        name:
          - podman
          - openvpn
          - stunnel

    - name: Include obs.yml
      ansible.builtin.include_tasks: ../common/obs.yml
