---

- name: Install jail.local
  ansible.builtin.copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart fail2ban

- name: Enable fail2ban service
  ansible.builtin.systemd_service:
    name: fail2ban
    enabled: true
    state: started
  ignore_errors: "{{ ansible_check_mode }}"
