---

- name: Restart sshd
  ansible.builtin.systemd_service:
    state: restarted
    name: sshd
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart chronyd
  ansible.builtin.systemd_service:
    state: restarted
    name: chronyd
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart kea-dhcp4
  ansible.builtin.systemd_service:
    state: restarted
    name: kea-dhcp4
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart squid
  ansible.builtin.systemd_service:
    state: restarted
    name: squid
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart httpd
  ansible.builtin.systemd_service:
    state: restarted
    name: httpd
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart fail2ban
  ansible.builtin.systemd_service:
    state: restarted
    name: fail2ban
  ignore_errors: "{{ ansible_check_mode }}"

- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"
