- name: repos.openhpc.community
  hosts: repos_aarch64
  become: yes
  gather_facts: True
  tasks:
  - name: install packages
    package:
      state: present
      name:
      - httpd
      - fail2ban-server
      - fail2ban-sendmail
      - goaccess
      - certbot
      - mod_ssl
      - rsync-daemon

  - name: Add the user 'ohpc'
    ansible.builtin.user:
      name: ohpc

  - name: create directories
    file: dest="{{item}}" mode=0755 state=directory owner=ohpc group=ohpc
    with_items:
    - /data
    - /rhel
    - /repos
    - /stats
    - /results

  - name: mount /data partition
    ansible.posix.mount:
      path: /data
      src: /dev/nvme1n1
      opts: defaults,noatime
      state: mounted
      fstype: xfs

  - name: create directories
    file: dest="/data{{item}}" mode=0755 state=directory owner=ohpc group=ohpc
    with_items:
    - /rhel
    - /rhel/repositories
    - /repos
    - /repos/.files
    - /stats
    - /results

  - name: create directories
    file: dest="/data{{item}}" mode=0755 state=directory owner=root group=root
    with_items:
    - /weblogs

  - name: "bind mount {{item}}"
    ansible.posix.mount:
      path: "{{item}}"
      src: "/data{{item}}"
      opts: bind
      state: mounted
      fstype: none
    with_items:
    - /rhel
    - /repos
    - /stats
    - /results

  - name: "bind mount /var/log/httpd"
    ansible.posix.mount:
      path: /var/log/httpd
      src: /data/weblogs
      opts: bind
      state: mounted
      fstype: none

  - name: install apache httpd config
    copy:
      src: "{{item}}"
      dest: "/etc/httpd/conf.d/{{item}}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - rhel.conf
      - repos.conf
      - stats.conf
      - results.conf
      - welcome.conf
      - ssl.conf
    register: httpd_conf

  - name: Allow apache to modify files in /stats
    community.general.sefcontext:
      target: '/stats(/.*)?'
      setype: httpd_sys_content_t
      state: present

  - name: Allow apache to modify files in /stats
    community.general.sefcontext:
      target: '/results(/.*)?'
      setype: httpd_sys_content_t
      state: present

  - name: Allow apache to modify files in /stats
    community.general.sefcontext:
      target: '/repos(/.*)?'
      setype: public_content_t
      state: present

  - name: Allow apache to modify files in /stats
    community.general.sefcontext:
      target: '/rhel/repositories(/.*)?'
      setype: httpd_sys_content_t
      state: present

  - name: Apply new SELinux file context to filesystem
    ansible.builtin.command: restorecon -irv /stats /repos /rhel/repositories /results /var/log/httpd

  - name: enable httpd service
    service: name=httpd enabled=yes state=started

  - name: Reload service httpd
    ansible.builtin.systemd_service:
      name: httpd.service
      state: reloaded
    when: httpd_conf.changed

  - name: install /repos HEADER.html
    copy:
      src: HEADER.html.repos
      dest: /repos/HEADER.html
      owner: root
      group: root
      mode: 0644

  - name: install certbot timer
    copy:
      src: "{{item}}"
      dest: /etc/systemd/system
      owner: root
      group: root
      mode: 0644
    with_items:
      - certbot-renewal.service
      - certbot-renewal.timer
    register: certbot_timer

  - name: systemd daemon-reload
    ansible.builtin.systemd:
      daemon_reload: true
    when: certbot_timer.changed

  - name: Enable certbot timer
    ansible.builtin.systemd_service:
      name: certbot-renewal.timer
      state: started
      enabled: true
    when: certbot_timer.changed

  - name: install http support files
    copy:
      src: "{{item}}"
      dest: /repos/.files/
      owner: root
      group: root
      mode: 0644
    with_items:
      - styles.css
      - test_error.png
      - test_ok.png
      - test_warning.png

  - name: install /results HEADER.tmpl
    copy:
      src: HEADER.tmpl
      dest: /home/ohpc/HEADER.tmpl
      owner: root
      group: root
      mode: 0644

  - name: install rsyncd.conf
    copy:
      src: rsyncd.conf
      dest: /etc/rsyncd.conf
      owner: root
      group: root
      mode: 0644
    register: rsyncd_conf

  - name: Enable rsyncd
    ansible.builtin.systemd_service:
      name: rsyncd
      state: started
      enabled: true
    when: rsyncd_conf.changed

  - name: install jail.local
    copy:
      src: jail.local
      dest: /etc/fail2ban/jail.local
      owner: root
      group: root
      mode: 0644
    register: jail_local

  - name: enable fail2ban service
    service: name=fail2ban enabled=yes state=started

  - name: Restart fail2ban
    ansible.builtin.systemd_service:
      state: restarted
      name: fail2ban
    when: jail_local.changed

  - name: install update_results.sh
    copy:
      src: update_results.sh
      dest: /home/ohpc/bin/update_results.sh
      owner: root
      group: root
      mode: 0755
