- name: repos.openhpc.community
  hosts: repos_aarch64
  become: yes
  gather_facts: True
  tasks:
  - name: install packages
    package:
      state: present
      name:
      - httpd
      - fail2ban
      - goaccess

  - name: Add the user 'ohpc'
    ansible.builtin.user:
      name: ohpc

  - name: create directories
    file: dest="{{item}}" mode=0755 state=directory owner=ohpc group=ohpc
    with_items:
    - /data
    - /rhel
    - /repos
    - /stats
    - /results

  - name: mount /data partition
    ansible.posix.mount:
      path: /data
      src: /dev/nvme1n1
      opts: defaults,noatime
      state: mounted
      fstype: xfs

  - name: create directories
    file: dest="/data{{item}}" mode=0755 state=directory owner=ohpc group=ohpc
    with_items:
    - /rhel
    - /rhel/repositories
    - /repos
    - /repos/.files
    - /stats
    - /results

  - name: create directories
    file: dest="/data{{item}}" mode=0755 state=directory owner=root group=root
    with_items:
    - /weblogs

  - name: "bind mount {{item}}"
    ansible.posix.mount:
      path: "{{item}}"
      src: "/data{{item}}"
      opts: bind
      state: mounted
      fstype: none
    with_items:
    - /rhel
    - /repos
    - /stats
    - /results

  - name: "bind mount /var/log/httpd"
    ansible.posix.mount:
      path: /var/log/httpd
      src: /data/weblogs
      opts: bind
      state: mounted
      fstype: none

  - name: install apache httpd config
    copy:
      src: "{{item}}"
      dest: "/etc/httpd/conf.d/{{item}}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - rhel.conf
      - repos.conf
      - stats.conf
      - results.conf
      - welcome.conf

  - name: Allow apache to modify files in /stats
    community.general.sefcontext:
      target: '/stats(/.*)?'
      setype: httpd_sys_content_t
      state: present

  - name: Allow apache to modify files in /stats
    community.general.sefcontext:
      target: '/results(/.*)?'
      setype: httpd_sys_content_t
      state: present

  - name: Allow apache to modify files in /stats
    community.general.sefcontext:
      target: '/repos(/.*)?'
      setype: httpd_sys_content_t
      state: present

  - name: Allow apache to modify files in /stats
    community.general.sefcontext:
      target: '/rhel/repositories(/.*)?'
      setype: httpd_sys_content_t
      state: present

  - name: Apply new SELinux file context to filesystem
    ansible.builtin.command: restorecon -irv /stats /repos /rhel/repositories /results /var/log/httpd

  - name: enable httpd service
    service: name=httpd enabled=yes state=started

  - name: install /repos HEADER.html
    copy:
      src: HEADER.html.repos
      dest: /repos/HEADER.html
      owner: root
      group: root
      mode: 0644

  - name: install http support files
    copy:
      src: "{{item}}"
      dest: /repos/.files/
      owner: root
      group: root
      mode: 0644
    with_items:
      - styles.css
      - test_error.png
      - test_ok.png
      - test_warning.png

  - name: install /results HEADER.tmpl
    copy:
      src: HEADER.tmpl
      dest: /home/ohpc/HEADER.tmpl
      owner: root
      group: root
      mode: 0644

  - name: install update_results.sh
    copy:
      src: update_results.sh
      dest: /home/ohpc/bin/update_results.sh
      owner: root
      group: root
      mode: 0755
